### ISSUE TITLE
Enrolment methods to courses not working

### ISSUE THREAD

**Issue by GoranFuru** [iomad/iomad#1265] opened 2020-01-27 09:19 UTC
Hi.

The only enrollment methods that seems to work in IOMAD is Manual, Self enrollment and License enrollment. Cohort sync and other enrollment methods does not work. Well users are enrolled to the courses with other enrollment methods but only from Moodle core perspective and not in IOMAD. The users cannot see the courses they are enroled to via Cohort sync. Is this a bug?

We are looking for a way to autoenrol users to courses but cannot see how this could be done in IOMAD. Any ideas?

**Comment by turf212** [comment] 2020-01-30 14:03
It's not a bug.  The Iomad courses block picks up it's information from the local_iomad_track tables for which courses a user has had access to.  Ths allows for course information to be displayed for users who may have undertaken the same course many times or may no longer be enrolled in and so on.

Can you confirm that thereis an entry in the this table for the user and course concerned?  If so, then we may need to change the block code to pick up the other enrolment types.

For autoenrolment within Iomad, you can define courses at a company level under advanced company settings, autoenrol courses, which will enrol anyone added to that company to these courses using the manual enrolment method.

**Comment by turf212** [comment] 2020-01-30 14:05
I should also say that adding someone to a cohort group is a site administrators task (as the users are site wide) so devolving this method of enrolment to a company manager will break the multi-tenancy.   Company managers can assign users to a course (using the manual enrolment type) and assign a license to a user (which then uses the license enrolment type) or a user can enrol themselves onto a course (using the self enrolment type).  Cohort enrolment doesn't lend itself to this.

**Comment by GoranFuru** [comment] 2020-01-30 15:53
Hi.

Thank's for the response. This is what we are trying to achieve "the big picture".

- We have one company with an organization structure e.g. departments and sub-departments.
- We have courses that are mandatory for certain departments and these should not be visible to other departments.
- The users are assigned to departments when they log in via Azure AD.
- After logging in the mandatory courses for each department should be visible in "My courses" on the dashboard as "In progress".
- Courses that are optional in the organization should be visible in "Available courses" as self enrolment.
E.g. full automation in adding users to companies, departments and enrolment to mandatory courses for specific departments.

To achieve this we have implemented the following methods:

- SAML2/Azure authentication/SSO
- Based on attributes on the user profile in Azure we perform SAML2 Data mapping to populate user_profile_fields for Company and Department.
- We have modified your Sign-up plugin to add the users in the corresponding Company and department.
- Then we use a plugin for automation of course enrolment to mandatory courses. This plugin uses the user_profile_fields for enrolling the users in different companies/departments to their mandatory courses.

Our approach works as expected regarding this automation. The problem is that even if the users are added to correct departments and enrolled into the correct courses, the users don't see the courses on their "My courses" block. The reason for this is that the enrolment method is not visible for IOMAD.
In our opinion this automation will not break the Multi Tennancy approach - rather enhance the automation process.

We have also a "QAD" approach for this (tried via db changes) and that approach is to change the enrolment method for the users as described above to "Manual" as soon as they log in (are enroled to the courses) and add a startdate - then the automation is complete... and the courses appears on the users dashboard.

Any ideas to fix this in automation in IOMAD or should we fix our own plugin for the course enrolment automation?

**Comment by turf212** [comment] 2020-02-06 00:09
Could you share your changes to the mapping for company/department  from the profile to company/department in the system please?  That looks to be a good improvement although it should probably have a control to decide which way round you want to do this.

From what you are saying, it sounds like you are falling foul because you aren't using an enrolment type which My Courses is looking for and you also don't have anything set for course completion criteria in the course itself.  When a user is marked as started on the system the get an entry in the local_iomad_track table which drives the my courses block and the reports.  So a better QAD approach would be to add an entry for the users into this table and leave the enrolment method alone.

We haven't done anything to keep courses away from departments.  Way back in Moodle 2.0 when we set departments up but the underpinnings of this have not been kept to as a lot of this is complex enough (how would you deal with a shared course or an open shared course, for example).  I'd be interested in how you are planning that too or is this all happening behind the scenes in the automation?

Actually - looking at the underlying code - (Iomad 3.7 latest) the workflow is as follows
- local/iomad_track has an observer for user_enrolment_created event.  This populates the local_iomad_track table with the appropriate time started values for the user/course.
- block_mycourses looks to this table and joins it with user_enrolments table for an active enrolment for that entry.  If there is one then it gets added to the list of current courses.

There is nothing in this code which filters on enrolment type.

Which version are you using?  3.6 will be the same as 3.7.  3.5 wont as this was all implemented when I updated all of the reports.

If it's 3.6 or 3.7 can you repeat the issue and, if so, can you give me the steps please?

**Comment by GoranFuru** [comment] 2020-02-12 16:05
Hi.

Of course we can share our new sign-up plugin.
Could we set up a web meeting to share our thoughts on automation of course enrollments for departments etc.

**Comment by bavdalimbaev** [comment] 2020-10-01 03:39
@GoranFuru  Hi, Can you help me with moodle iomad?. I have any question.

**Comment by GoranFuru** [comment] 2020-10-01 06:35
Hi.

How can I help you out?

Kind regards,
Göran

_______________________________________________

[cid:image001.jpg@01D697CD.C0A8B4E0]
Göran Furu
Learning and Performance Consultant
goran.furu@maincon.se<mailto:goran.furu@maincon.se>
Mobile +46 70 686 95 64
www.maincon.se<http://www.maincon.se>


Från: Bekjan Avdalimbaev <notifications@github.com>
Skickat: den 1 oktober 2020 05:39
Till: iomad/iomad <iomad@noreply.github.com>
Kopia: Göran Furu <goran.furu@maincon.se>; Mention <mention@noreply.github.com>
Ämne: Re: [iomad/iomad] Enrolment methods to courses not working (#1265)


@GoranFuru<https://github.com/GoranFuru> Hi, Can you help me with moodle iomad?. I have any question.

**Comment by bavdalimbaev** [comment] 2020-10-01 08:56
Thank you. 

users can login with only phone in iomad/moodle after success signup? and how?
how in iomad/moodle, Admin can show course for all company after create course?
After create 3 company how i can divide on subdomain.domain.com every company? OR simpler on page  {signup} how i can add {select options company} before registering? 

please, if you can help. could you write my mail. or send please your

**Comment by GoranFuru** [comment] 2020-10-01 11:46
Hi.

Sorry. We cannot support you in these queries.

Kind regards,
Göran

_______________________________________________

[cid:image001.jpg@01D697F9.4B3C1D10]
Göran Furu
Learning and Performance Consultant
goran.furu@maincon.se<mailto:goran.furu@maincon.se>
Mobile +46 70 686 95 64
www.maincon.se<http://www.maincon.se>


Från: Bekjan Avdalimbaev <notifications@github.com>
Skickat: den 1 oktober 2020 10:56
Till: iomad/iomad <iomad@noreply.github.com>
Kopia: Göran Furu <goran.furu@maincon.se>; Mention <mention@noreply.github.com>
Ämne: Re: [iomad/iomad] Enrolment methods to courses not working (#1265)


Thank you.

users can login with only phone in iomad/moodle after success signup? and how?
how in iomad/moodle, Admin can show course for all company after create course?
After create 3 company how i can divide on subdomain.domain.com every company? OR simpler on page {signup} how i can add {select options company} before registering?

please, if you can help. could you write my mail. or send please your

**Comment by ShawnWhy** [comment] 2023-01-03 16:32
Hi I think I might have figured this out, in blocks-mycourses-locallib.php line 47 the in-progess view asks for courses that has a user_enrolments table timestart !=0 

when we enrol people without using the iomad tools, it automatically assigns a 0 to that field. I took out that line and the courses will show up. I wonder if this will obstruct the work flow though

**Comment by turf212** [comment] 2024-11-25 16:31
Enrolment timestart should be set? It should equal time created if nothing else.

**Closed as completed by turf212** 2024-11-25 16:31 UTC
