### ISSUE TITLE
Error when editing user details from dashboard 

### ISSUE THREAD

**Issue by Melly78** [iomad/iomad#1448] opened 2020-08-28 05:57 UTC
When i go to dashboard --> Users --> Edit users --> (under user details) user controls --> Edit

i get the attached error message

Can anyone assist with this?? i don't have coding experience so i can't help or assist where this is going wrong. 

![Capture](https://user-images.githubusercontent.com/60528025/91526514-26230300-e947-11ea-9ad8-d11d31e39611.PNG)

**Comment by turf212** [comment] 2020-09-08 21:02
which version are you using?  I've checked this on latest 3.6/7 and 8 and not getting any error messages.  I would suggest upgrading/patching to the latest versions.

If it's still happening: To see more information from the fairly useless error message, go to site administration -> development -> debugging, switch on full developer debug and tick the option to show in the browser.  This will show the full debug information including the file and line of code that's going wrong.

**Comment by turf212** [comment] 2020-09-17 15:21
closing as not a bug as not heard anything back and can't replicate.

**Closed as completed by turf212** 2020-09-17 15:21 UTC
Labels: Not a bug
