### ISSUE TITLE
404 error where using different webserver hostnames for each company

### ISSUE THREAD

**Issue by SebaAndreu** [iomad/iomad#1433] opened 2020-07-25 02:43 UTC
Hi!

Just installed IOMAD to test how multi-tenancy works with different webserver hostnames but I'm getting a redirected URL that doesn't work.

Example:
- Main IOMAD server has name1.com
- Company ABC created and needs to get access to their Moodle environment through "abc.name1.com" son configured "Webserver hostname" with that name
- Tried accesing to "abc.name1.com" and system is returning "abc.name1.com/%3A//://abc.name1.com/login/index.php?id=2&code=ABC", login not showing and instead having 404 error

----------
Server Error

404 - File or directory not found.
The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.
----------

Does anyone can help me to understand what's happening?

Thanks

**Comment by turf212** [comment] 2020-09-08 22:25
it looks like the hostname you are using is possibly using the http:// parts when it should just be the hostname - abc.name1.com.  If you look at the https://demo.iomad.org site you will see how this is set up for a couple of companies.

**Comment by mohgh** [comment] 2020-10-11 11:35
I have the exact same problem. I have used sub.mydomain.com in iomad dashboard without any http or https at the first part.
I'm using IIS for hosting iomad.

**Comment by mohgh** [comment] 2020-10-11 13:00
The problem is related to this line in code:
`$CFG->wwwroot   = $_SERVER['REQUEST_SCHEME'] . "://" . $_SERVER["SERVER_NAME"];`
the part `$_SERVER['REQUEST_SCHEME']` is not resolved to a scheme using IIS.

**Comment by turf212** [comment] 2020-10-13 09:33
Ah, thanks for the heads up.  I was using the Moodle code to try and work out if the original call was over HTTPS or not.  Obviously that doesn't work with IIS.

**Comment by turf212** [comment] 2020-10-13 09:46
I've pushed a fix for this which will work on all webservers.

**Comment by imhemantpahadi** [comment] 2021-01-30 18:23
> Hi!
> 
> Just installed IOMAD to test how multi-tenancy works with different webserver hostnames but I'm getting a redirected URL that doesn't work.
> 
> Example:
> 
> * Main IOMAD server has name1.com
> * Company ABC created and needs to get access to their Moodle environment through "abc.name1.com" son configured "Webserver hostname" with that name
> * Tried accesing to "abc.name1.com" and system is returning "abc.name1.com/%3A//://abc.name1.com/login/index.php?id=2&code=ABC", login not showing and instead having 404 error
> 
> Server Error
> 
> ## 404 - File or directory not found.
> The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.
> Does anyone can help me to understand what's happening?
> 
> Thanks

You need to add A record in your domain dns section
like this *.abc.com once it added in the domain dns then you will able to access the company hostname

**Closed as completed** 2024-11-24 01:24 UTC
Labels: Question, Not a bug
