### ISSUE TITLE
Webservice block_iomad_company_admin_assign_users throws dmlwriteexception

### ISSUE THREAD

**Issue by abias** [iomad/iomad#1694] opened 2022-05-23 09:51 UTC
Prerequisites:
* Do everything necessary to run a webservice call with the webservice functions core_user_create_users and  block_iomad_company_admin_assign_users (Enable webservices, create a webservice user, allow webservice function, generate webservice token...)

Steps to reproduce:
* Call the core_user_create_users function to create a plain Moodle user:
https://youriomad.org/webservice/rest/server.php?wsfunction=core_user_create_users&wstoken=yourtoken&moodlewsrestformat=json&users[0][username]=foo&users[0][firstname]=Foo&users[0][lastname]=Bar&users[0][email]=foo@bar.com&users[0][createpassword]=1
* Note the Moodle user ID which you get back from the webservice call
* Call the block_iomad_company_admin_assign_users function to add the plain Moodle user (in this example with the ID 12345) to a company:
https://youriomad.org/webservice/rest/server.php?wsfunction=block_iomad_company_admin_assign_users&wstoken=yourtoken&moodlewsrestformat=json&users[0][userid]=12345&users[0][companyid]=1&users[0][educator]=0&users[0][managertype]=0&users[0][departmentid]=1

Expected result:
* The webservice call suceeds
* The user is a member of the company

Actual result:
* The webservice call fails with a dmlwriteexception
```
{
    "exception": "dml_write_exception",
    "errorcode": "dmlwriteexception",
    "message": "Fehler beim Schreiben der Datenbank",
    "debuginfo": "Column 'educator' cannot be null\nINSERT INTO mdl_company_users (companyid,userid,departmentid,educator,managertype) VALUES(?,?,?,?,?)\n[array (\n  0 => 1,\n  1 => 12345,\n  2 => 1,\n  3 => NULL,\n  4 => 0,\n)]"
}
```
* The user isn't a member of the company

Analysis:
This actual result is a clear bug and should be solved by this patch:
```
diff --git a/blocks/iomad_company_admin/externallib.php b/blocks/iomad_company_admin/externallib.php
index ae70638275c..557a05283d8 100755
--- a/blocks/iomad_company_admin/externallib.php
+++ b/blocks/iomad_company_admin/externallib.php
@@ -737,7 +737,13 @@ class block_iomad_company_admin_external extends external_api {
                                               $company->id,
                                                $userrecord['departmentid'],
                                                $userrecord['managertype'],
-                                               null,
+                                               $userrecord['educator'],
                  $succeeded = false;
                  $errormessage = "Unable to assign user";
```

As this bug affects multiple release branches, I won't create a pull request and will leave it up to the maintainers to fix all supported branches.

**Comment by turf212** [comment] 2022-08-03 15:56
Duplicate of #1641 #1635  and fixed in commit 4afc5fdd86490ae942d2088a53d4a28bc057dbba

**Closed as completed by turf212** 2022-08-03 15:56 UTC
