### ISSUE TITLE
Error when creating a new company

### ISSUE THREAD

**Issue by tzumtobel** [iomad/iomad#698] opened 2017-09-07 09:21 UTC
Notice: Undefined variable: company in /var/www/iomad.lab/blocks/iomad_company_admin/company_edit_form.php on line 674

Fatal error: Call to a member function assign_role_templates() on null in /var/www/iomad.lab/blocks/iomad_company_admin/company_edit_form.php on line 674

brand new installation.

**Comment by turf212** [comment] 2017-09-07 11:20
this is a duplicate of #694

**Comment by turf212** [comment] 2017-09-07 11:21
Code to fix this was pushed to github yesterday.  When did you pull this version?

**Comment by tzumtobel** [comment] 2017-09-08 07:13
I just pulled the code again - some error.

**Comment by turf212** [comment] 2017-09-09 16:19
Ah, this is 3.3 code.  Looks like the cherry-pick into that branch didn't work.

**Closed as completed** 2017-09-09 16:25 UTC
Labels: Duplicate
