### ISSUE TITLE
Is this an issue or a department can have only one user while creating a user and assigning role other than user role?

### ISSUE THREAD

**Issue by sheetal071** [iomad/iomad#1788] opened 2023-03-27 12:16 UTC
Iomad version: 4.1.2

Steps to recreate:
Assign role which is other than User role to more than one user while creating the user. Then the below error message will be shown but user will be created successfully.
![image](https://user-images.githubusercontent.com/108781673/227938424-58cf48ac-8a7e-457c-9056-79725eb6cc4c.png)

**Comment by turf212** [comment] 2023-03-29 17:17
A user can only exist in multiple departments as a department manager or a user.  What role were you assigning the user on creation?  You can also only select one department at a time on that page so how are you getting mutiple departments?

**Comment by sheetal071** [comment] 2023-03-30 07:56
Actually the above error was thrown but the user was created successfully for the respected department. The above error was thrown when I had created the user and assigned department training manager role also selected sub department of a company while creating the user.

**Comment by turf212** [comment] 2024-11-25 11:21
Duplicate of #1795

**Closed as completed by turf212** 2024-11-25 11:21 UTC
