### ISSUE TITLE
error when assigning external company manager (invaliduserdepartment)

### ISSUE THREAD

**Issue by jonno65** [iomad/iomad#294] opened 2015-10-23 09:41 UTC
Hi,

I'm getting the following error message when trying to assign an external company manager:

block_iomad_company_management/invaliduserdepartment

The account is a member of another company and is a company manager for that company
When trying to assign this account as a company manager to a different company, above error message is generated. Have tried multiple user accounts with different companies all give the same error message.

I'm on Iomad v2.9; Moodle 2.9.2 (Build: 20150914).
I recently upgraded from Iomad v2.8 Moodle 2.8.5+ (Build: 20150417)

Any ideas on how to fix?

Thanks,
John

**Comment by ehuggett** [comment] 2015-11-30 13:32
I think the following patch will address your issue.

The problem was that external company managers are not a valid user of the current company (and a check for this was recently added to prevent various shenanigans). The patch extends the check to consider the case of an external company manager.

note: it also fixes a typo that was preventing user roles from being unassigned.

```
diff --git a/blocks/iomad_company_admin/company_managers_form.php b/blocks/iomad_company_admin/company_managers_form.php
index dc132c0..0c911ee 100644
--- a/blocks/iomad_company_admin/company_managers_form.php
+++ b/blocks/iomad_company_admin/company_managers_form.php
@@ -160,7 +160,20 @@ class company_managers_form extends moodleform {

                 // Check the userid is valid.
                 if (!company::check_valid_user($this->selectedcompany, $adduser->id, $this->departmentid)) {
-                    print_error('invaliduserdepartment', 'block_iomad_company_management');
+                    // The userid may still be valid, but only if we are assigning an external company manager
+                    // require permissions, check roletype is manager & the userid is actually a manager in another company
+                    if (!(iomad::has_capability('block/iomad_company_admin:company_add', context_system::instance()) && $roletype == 1 &&
+                          $DB->get_records_sql('SELECT id FROM {company_users}
+                                                WHERE
+                                                userid = :userid
+                                                AND managertype = :roletype
+                                                AND companyid != :companyid', array('userid' => $adduser->id,
+                                                                                    'roletype' => 1,
+                                                                                    'companyid' => $this->selectedcompany))
+                       )) {
+                              // We are not assigning an external company manager AND the userid is not valid for this company
+                              print_error('invaliduserdepartment', 'block_iomad_company_management');
+                          }
                 }

                 if ($allow) {
@@ -318,7 +331,7 @@ class company_managers_form extends moodleform {
                     foreach ($userstounassign as $removeuser) {

                         // Check the userid is valid.
-                        if (!company::check_valid_user($this->selectedcompany, $adduser->id, $this->departmentid)) {
+                        if (!company::check_valid_user($this->selectedcompany, $removeuser->id, $this->departmentid)) {
                             print_error('invaliduserdepartment', 'block_iomad_company_management');
                         }
```

**Comment by jonno65** [comment] 2015-11-30 21:27
Hi,

Many thanks for this! The patch did indeed solve the error message from displaying and I am now able to assign Company Managers from different companies. On the Iomad dashboard of that user, the other companies are available in the 'select a company' drop-down box. However, when I select any other company, after the page reloads, the selection reverts back to the company of which the user is originally a member of. The user is unable to select any other company to manage.

Should I close this issue and open a new one?

Regards,
John

**Comment by ehuggett** [comment] 2015-12-01 12:34
It might be best to keep this issue open until merge #299 is accepted (or the issue is fixed another way), I'm not 100% sure to be honest.

Unless issues are very closely related its normally best to start a new ticket, as this allows the project author to close them individually as they are patched.

PS looking at iomad/local_dashboard/index.php line 38 setting the company to edit requires the "block/iomad_company_admin:company_add" role/permission. If your user already has this role, or if this role is not appropriate for the user (as, based on the name, it lets them create new companies) I would open a new issue with a suggestion for a more appropriate role/permission if you can... its a one line change so if you know what you want to change it to you could have a go at submitting a patch/merge request too :)

**Comment by jonno65** [comment] 2015-12-10 21:23
Thanks for pointing me in the right direction. Initially I tried setting the "Add Company" permission to "Allow" for the "Company Manager" role. The effect however was that the user could manage ALL companies which was unwanted.

I then tried changing the requirement on line 38 to:
"block/iomad_company_admin:company_manager", which is the right requirement I think and hey presto, everything is working as expected!

I have no idea on how to submit this patch though.

**Comment by turf212** [comment] 2015-12-11 14:28
I've been neglecting this a little recently but will be spending a bit of time over the next couple of weeks working through issues and working on the version on Moodle 3.0.  Thanks for your patience and support!

**Comment by f00k** [comment] 2016-02-05 14:13
@turf212 - Good luck with the new version. Do you have any updates?

**Comment by canyasa** [comment] 2016-02-11 15:19
Hi everyone, I am having the same assigning issue but my error is different. (I also updated that codes above). Any ideas?

Moodle 2.9.2 (Build: 20150914)
Iomad 2.9
Here is my error:

Coding error detected, it must be fixed by a programmer: invalid enrol instance!

More information about this error

Debug info: 
Error code: codingerror
Stack trace:
line 1292 of \lib\enrollib.php: coding_exception thrown
line 297 of \local\iomad\lib\user.php: call to enrol_plugin->enrol_user()
line 221 of \blocks\iomad_company_admin\company_managers_form.php: call to company_user::enrol()
line 440 of \blocks\iomad_company_admin\company_managers_form.php: call to company_managers_form->process()

**Comment by ehuggett** [comment] 2016-02-12 10:56
Canyasa, (honest, trying to help question) what makes you think you issue is similar enough to the original issue to comment on it?

The patch I included above was intended to fix a very specific issue, which does not sound like the one you are having. If I was you, I would remove that patch if you don't currently need the ability to assign external company managers as diverging from 'official' IOMAD releases without good reason may cause unnecessary problems for you in the future.

Unless I am wrong about your issue being different, would you mind opening a new issue for this and re-posting it? some extra details as to the steps you have to take to cause the error would also be helpful

**Comment by canyasa** [comment] 2016-02-12 14:49
I thought that was it, cause that patch worked on my local I could assign users or managers without an error, but before it wasn't working. However it didn't work on server, you are right I should do that thanks.

**Comment by turf212** [comment] 2016-03-07 10:33
This is being incorporated into the 3.0 version.  Thanks for the work on this.

**Closed as completed** 2016-03-16 20:19 UTC
