### ISSUE TITLE
Cloned theme - can´t edit company

### ISSUE THREAD

**Issue by MathiasLarsson** [iomad/iomad#52] opened 2014-04-07 12:08 UTC
Hi there! Hope its ok to speak to you about a issue i have with Iomad. I just cloned the Aardvark theme and it works fine- but when i try to edit/add a company i got a blank page. 
Anybody have a clue what i´m doing wrong?

**Comment by MathiasLarsson** [comment] 2014-04-08 09:27
Anybody?

**Comment by turf212** [comment] 2014-04-08 09:40
Can you turn debugging on on the site and post any debug information you may receive when you go to that page?  We have used this with the Aardvark theme successfully in the past and it may be something else which is failing.

Thanks

**Comment by MathiasLarsson** [comment] 2014-04-08 10:23
Ok i will do that! Thanx in advance!

**Comment by MathiasLarsson** [comment] 2014-04-08 10:32
Hi, got this error message:

Fatal error: Cannot redeclare aardvark_process_css() (previously declared in /home/webatonc/public_html/moodle/theme/aardvark/lib.php:9) in /home/webatonc/public_html/moodle/theme/aardvark2/lib.php on line 69

**Comment by MathiasLarsson** [comment] 2014-04-08 11:05
I solved the problem by renaming lib.php. Thanx anyway! Please look at my report-problem! Thanx in advance!

**Comment by turf212** [comment] 2014-04-08 12:26
The issue is due to how you have cloned the Aardvark theme not to do with Iomad/Moodle.  Basically you have the same class defined in the cloned theme as you did in the original theme (which you removed by deleting the lib.php file).  You are better using child themes to do this instead of fully cloning a theme as then the child themes pick up any patches to the main theme.  You may need to read the Moodle theme development pages to understand how to do this.

In any case, its not an issue so I will close this :)

**Closed as completed by turf212** 2014-04-08 12:26 UTC
Labels: Invalid

**Comment by MathiasLarsson** [comment] 2014-04-08 12:28
I made some more changes in the lib.php/settings.php - from now the both themes work as individual themes.
