### ISSUE TITLE
SCORM V1.2 courses not grading PLEASE HELP

### ISSUE THREAD

**Issue by ludz007** [iomad/iomad#1858] opened 2023-07-01 10:56 UTC
Hi There

I hope that someone can assist me.

We have over 140 scorm v1.2 courses (that was compiled through articulate) on our platform...

But for some unknown reason.. some of the learners are experiencing a problem where:

- they cannot resume where they left off (lets say they did up to module 7 but when they log out and back in it resumes them to module 3)
- courses are not graded correctly, so lets say that they have received 85%, it only shows as 20% and now they are not awarded a certificate 
Can someone please assist me?

Auto commit is turned on for every course aswell...

Ive tried everything

**Comment by dallenk** [comment] 2023-07-05 18:36
I had a similar issue, does the 'complete report' shed any light on a course that is completed or otherwise in-progress??

cmi.core.exit => suspend
cmi.core.lesson_location => 5324503
cmi.core.lesson_status => completed
cmi.core.total_time => 00:23:11.00
cmi.suspend_data => 5324474,5324475,[lots more]

**Comment by roberta-wm** [comment] 2023-08-01 08:49
Hi,
I don't know if it's related but we have a similiar problem with SCORMs on a LMS Moodle-IOMAD 4.1. My students completes a SCORM. If I look at the SCORM report, status is "completed" but the actvity SCORM package doesnt' show any completion flag on the course page and there's no completion log in the log report.
The same SCORM works perfectly on a Moodle-IOMAD LMS version 3.9. In both cases, the settings require a "completed" or "passed" status to be considered completed.

**Comment by turf212** [comment] 2023-10-02 14:44
It looks like this was caused by a comment in one of the observers.  I've just pushed a fix under 2e77b8c44c4d580a71bc001c7fcabf5d5812d9eb to the 4.1 and 4.2 branches

**Closed as completed** 2024-11-24 14:26 UTC
