### ISSUE TITLE
Manager can't see courses in manage courses and categories

### ISSUE THREAD

**Issue by Ayasaad** [iomad/iomad#880] opened 2018-02-26 08:02 UTC
How can i allow user with a site role manager to be able to view the courses and categories , i understand that in iomad the courses must be open shared so the manager can see them , but i was wondering which part in the code can be changed to allow the manager to see courses in manage courses and categories like in normal moodle .

Please note that i don't want to give this user a site administration role .

**Comment by sahil1** [comment] 2019-03-13 01:40
@Ayasaad Have you checked https://docs.moodle.org/36/en/Manager_role
**Assigning the role of Manager at the Category level**

Assign this as follows: Site administration > Courses > Add/edit courses > (select a category) > Edit this category > Administration block: Assign roles > Manager > (select user) Add

**Comment by turf212** [comment] 2019-03-13 20:39
The issue is that, if you don't allow the site manager role something like iomad_company_admin/company_view_all or assign the user to a company, then the user will have issues with the course categories as these are being filtered by the company a user is in.  You definitely need to play with that role to get it to work as you expect.

**Closed as completed by turf212** 2019-03-13 20:39 UTC
