### ISSUE TITLE
Reminder emails do not add hostname to placeholders

### ISSUE THREAD

**Issue by tom5850** [iomad/iomad#2007] opened 2024-07-13 10:44 UTC
We are using hostnames for each tenant. Emails that are created automatically like reminder emails (e.g. completion_warn_user)  do not add the hostname to the placeholders SiteURL and CourseURL.

This is because at the moment, when the function get_wwwroot() from file local/iomad/lib/company.php is called, no company context is available.

**Comment by tom5850** [comment] 2024-07-17 09:55
After further analysis we found that also the sender address is not taken from user's company, but from company 1.

Does anybody else face those issues?

**Comment by turf212** [comment] 2024-11-18 09:14
This is a duplicate of #1960  and fixed in commit 95ec69130813aff9da19b19ac186574610a6ea40

**Closed as completed** 2024-11-18 09:14 UTC
