### ISSUE TITLE
3.4-3.6 update error

### ISSUE THREAD

**Issue by syusanjun** [iomad/iomad#1091] opened 2019-03-07 08:21 UTC
We upgraded from 3.4 to 3.6.
Course category screen can not be displayed with error.

Can not find data record in database table course_categories.
More information about this error
×Debug info: SELECT id,parent FROM {course_categories} WHERE id = ?
[array (
0 => 0,
)]
Error code: invalidrecord
×Stack trace:
line 1546 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown
line 1522 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
line 6512 of /lib/accesslib.php: call to moodle_database->get_record()
line 73 of /course/management.php: call to context_coursecat::instance()
×Output buffer: <br /> <b>Notice</b>: Undefined offset: 0 in <b>/var/www/html/moodle/course/classes/category.php</b> on line <b>354</b><br />

**Comment by turf212** [comment] 2019-03-07 11:18
Sounds like a data issue in your company definitions.

Each company should have a course category created for them with the same name as the company shortname.  This is stored in the mdl_company record for the company in the category column (its the id for the category).

If you sort that data out before upgrading and then re-run the upgrade it will work.

**Comment by syusanjun** [comment] 2019-03-07 23:52
Thank you

Can I delete an organization?
Even if you delete a category, the organization will remain in iomad dashbord.

**Comment by shariffmohamed** [comment] 2019-03-12 09:08
I am getting the same error today with a new installation of 3.6.

It was working and this morning started with the error messages.
I've tried setting up an entire new site from scratch on another test domain and it immediately give the error

**Comment by sahil1** [comment] 2019-03-12 19:11
Able to replicate on fresh install of 3.6
1) Create New Company
2) Go to Site Admin -> Courses -> Manage courses and categories

The default URL is /course/management.php which results in the error as function get_records expects categoryid param

If you manually change the URL to /course/management.php?categoryid=1 i.e. pass categoryid then it loads without any error. Ideally would like to see site admin be able to access to all the categories.

**Comment by turf212** [comment] 2019-03-12 22:28
@syusanjun  - No you can't delete an organisation.  You can suspend them and then they will be removed from the menus unless you specify to show the suspended companies as well.

@shariffmohamed - You must have deleted a category which was in use by a company. There was another issue on installation due to the recent 3.6.3 Moodle patches uploaded yesterday.  This was fixed in #1101

If you can outline exactly what you did I can test but the only way i've seen the database error about categories is if you delete one.

**Comment by shariffmohamed** [comment] 2019-03-13 04:37
I've tried the following this morning

- Deleted all public files
- Deleted moodledata folder
- Emptied database
- Deployed branch IOMAD_36_STABLE from repo
- Ran through the wizard
- No errors or recommendations during server checks
- Completed installation / setup

Entered first company and went to Site Admin > Courses > Manage courses and categories and got the error.

If I try what @sahil1 suggested of adding "?categoryid=1" to the URL I don't get an error but I also don't see the company I just added

In the DB the company exists in the mdl_company table and the category for the company exists in the mdl_course_categories

**Comment by sahil1** [comment] 2019-03-13 13:51
@shariffmohamed categoryid=1 is Misc category. To see the category for company you can change the id value to that specific category. I am using this as a workaround for now.

**Comment by turf212** [comment] 2019-03-13 21:03
Thanks for giving the directions.  Something going wrong with the filtering of the course catalogue.

**Comment by dthies** [comment] 2019-03-15 20:17
I think the may be a result of deleting a course which should be fixed by https://github.com/iomad/iomad/pull/1097. I which case upgrading to latest 3.6 version should fix the problem.

**Comment by deepaksharma0311** [comment] 2019-03-18 10:05
I am facing the same issue. Dont know how to view all categories.

**Comment by turf212** [comment] 2019-03-18 20:37
The issue is due to the admin account not being tied to a company and the logic not coping with it for the changes in the course category classes in 3.6.

**Closed as completed** 2019-03-18 20:38 UTC
