### ISSUE TITLE
Logged in as company manager http://..../moodle/course page doesn't work properly

### ISSUE THREAD

**Issue by thepurpleblob** [iomad/iomad#81] opened 2014-04-12 12:03 UTC
(Trying this as medicine manager in moot course). I was trying to get a full list of "my" courses and couldn't find any place to do this (which could be a problem in itself) so went to this page directly. 

The page shows the medicine category (only). When expanding the category, it only shows one course (Theatre Access in this case). However, I know there are more because I've seen them in reports.

There's also a link beneath the category "View more". Clicking this results in a coding error...

Coding error detected, it must be fixed by a programmer: moodle_database::get_in_or_equal() does not accept empty arrays

**Comment by turf212** [comment] 2014-08-05 20:58
This is a duplicate of #110

**Closed as completed by turf212** 2014-08-05 20:58 UTC
Labels: Duplicate
