### ISSUE TITLE
user profile page error, and missing information

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1773] opened 2023-03-13 05:43 UTC
most current 401_stable code. (debugging enabled)
When company manager views a user profile page some profile information is missing (Department, ID number)   I am using LDAP authentication and datamapping(if that makes a difference).   The Administrator can view all the profile information and no error is shown.

```
Coding problem: $PAGE->context was not set. You may have forgotten to call require_login() or $PAGE->set_context(). The page may not display correctly as a result

    line 567 of /lib/pagelib.php: call to debugging()
    line 962 of /lib/pagelib.php: call to moodle_page->magic_get_context()
    line 1466 of /lib/weblib.php: call to moodle_page->__get()
    line 2115 of /local/iomad/lib/company.php: call to format_string()
    line 2149 of /local/iomad/lib/company.php: call to company::get_all_subdepartments()
    line 2186 of /local/iomad/lib/company.php: call to company::get_recursive_department_users()
    line 3571 of /local/iomad/lib/company.php: call to company::get_my_users()
    line 79 of /user/profile.php: call to company::check_can_manage()

```

**Comment by turf212** [comment] 2024-11-25 11:29
duplicate of #2058

**Closed as completed by turf212** 2024-11-25 11:29 UTC
