### ISSUE TITLE
Coding error detected on assigning users as a manager

### ISSUE THREAD

**Issue by canyasa** [iomad/iomad#310] opened 2016-02-12 14:55 UTC
I can not assign users as a manager to a sub company, having this error:

Moodle 2.9.2 (Build: 20150914)
Iomad 2.9 (No patches added)

Coding error detected, it must be fixed by a programmer: invalid enrol instance!

Debug info: 
Error code: codingerror
Stack trace:
line 1292 of \lib\enrollib.php: coding_exception thrown
line 297 of \local\iomad\lib\user.php: call to enrol_plugin->enrol_user()
line 208 of \blocks\iomad_company_admin\company_managers_form.php: call to company_user::enrol()
line 427 of \blocks\iomad_company_admin\company_managers_form.php: call to company_managers_form->process()

Any Ideas? Thank you.

**Comment by ehuggett** [comment] 2016-02-16 14:22
1. What's changed since this last worked?
2. when did this last work?
3. does this happen with other companies / sub departments
4. have you deleted/removed/disabled/updated any courses recently?
5. have you also had any problems assigning staff members onto any courses recently?
6. Can you enable debugging to see if you get any extra information? (Site Administration -> Development -> Debugging, set debug to DEVELOPER and enable debugdisplay)

I've run out of time for now, here's my notes

```
// Deal with company courses.
                                    if ($companycourses = $DB->get_records('company_course',
                                                                            array('companyid' => $this->selectedcompany))) {
                                        foreach ($companycourses as $companycourse) {
                                            if ($DB->record_exists('course', array('id' => $companycourse->courseid))) {
                                                if ($DB->record_exists('company_created_courses',
                                                                        array('companyid' => $companycourse->companyid,
                                                                              'courseid' => $companycourse->courseid))) {
                                                    company_user::enrol($adduser,
                                                                        array($companycourse->courseid),
                                                                        $companycourse->companyid,
                                                                        $companycourseeditorrole->id);
                                                } else {
LINE208>                                     company_user::enrol($adduser,
                                                                        array($companycourse->courseid),
                                                                        $companycourse->companyid,
                                                                        $companycoursenoneditorrole->id);
                                                }
                                            }
                                        }
                                    }
```

Since company_user::enrol was called I know that (from following the if statements)
- at least one course is assigned to the company 
- the course assigned to the company still exists in the courses table
- its not a "company created course" (if the line number in the stack trace, line 208, is accurate)

It seems your problem is not being caused by assigning the manager role, but with enrolling the manager onto one of the company courses (which happens as part of assigning the manager role).

**Comment by canyasa** [comment] 2016-02-16 14:56
Thanks ehuggett,
1.What's changed since this last worked?
- as coding nothing has changed

2.When did this last work?
- It used to work a month ago, we have a training guy that uploads and creates courses. That is all.

3.Does this happen with other companies / sub departments
- Yes I tried all the companies and sub depts, none of them works.

4.Have you deleted/removed/disabled/updated any courses recently?
- The only change was on one of the course's completion settings.

5.Have you also had any problems assigning staff members onto any courses recently?
- I have no problem assigning users to a course or company.

6.Can you enable debugging to see if you get any extra information?
- Still having the same error above.

I have tried with different companies, different users. I can assign users to a company, I just can not assign users as manager (company manager or training manager, doesn't matter, having the same error.). 

EDIT; 

Also I am having this error when I try to remove a manager;

> Debug info: 
> Error code: invaliduserdepartment 
> $a contents:
> Stack trace:
> line 481 of \lib\setuplib.php: moodle_exception thrown
> line 322 of \blocks\iomad_company_admin\company_managers_form.php: call to print_error()
> line 427 of \blocks\iomad_company_admin\company_managers_form.php: call to company_managers_form->process()
> Output buffer: Notice: Undefined variable: adduser in D:\Training\blocks\iomad_company_admin\company_managers_form.php on line 321 Notice: Trying to get property of non-object in D:\Training\blocks\iomad_company_admin\company_managers_form.php on line 321

**Comment by ehuggett** [comment] 2016-02-16 16:25
I've had a look at "line 297 of \local\iomad\lib\user.php: call to enrol_plugin->enrol_user()"

I don't completely understand what its doing / why it does it, but if i was asked for an educated guess i would say Its likely one of the courses is causing/triggering the problem, specificity the order of enrolment methods for one of the courses. (hopefully just one anyway, never assume you only have one problem!).

I don't know how many courses you have, but starting with the most recently modified/added I would check "Course Administration > Users > Enrolment methods" and see if its set-up differently from your oldest course (or rather, the one that has not been edited for the longest as its the least likely course to be causing the problem).

Pay special attention to the _first_ enrolment method on the list, I think that's the only one that matters based on what I was reading but I'm really not sure so pay attention to them all!

**Comment by canyasa** [comment] 2016-02-17 15:52
ehuggett, I found that they have created cohorts from moodle>admin>users>... Do you think could it be the problem?

Update: No, it is not. Still having the error :confused: 

By the way, we have 96 courses.

+

I just made a clean install on my local to test, I was able to assign user as manager but when I try to unassign from department training manager; had this error;

block_iomad_company_management/invaliduserdepartment

More information about this error

> Debug info: 
> Error code: invaliduserdepartment 
> $a contents:
> Stack trace:
> line 481 of \lib\setuplib.php: moodle_exception thrown
> line 322 of \blocks\iomad_company_admin\company_managers_form.php: call to print_error()
> line 427 of \blocks\iomad_company_admin\company_managers_form.php: call to company_managers_form->process()
> Output buffer: <br /> <b>Notice</b>: Undefined variable: adduser in <b>C:\xampp\htdocs\iomad\blocks\iomad_company_admin\company_managers_form.php</b> on line <b>321</b><br /> <br /> <b>Notice</b>: Trying to get property of non-object in <b>C:\xampp\htdocs\iomad\blocks\iomad_company_admin\company_managers_form.php</b> on line <b>321</b><br />

Update:
When I try to create a new dept. training manager from iomad, having this error but it creates the manager.

> Coding error detected, it must be fixed by a programmer: invalid enrol instance!
> 
> More information about this error
> 
> Debug info: 
> Error code: codingerror
> Stack trace:
> line 1292 of \lib\enrollib.php: coding_exception thrown
> line 297 of \local\iomad\lib\user.php: call to enrol_plugin->enrol_user()
> line 422 of \blocks\iomad_company_admin\company_user_create_form.php: call to company_user::enrol()

**Comment by ehuggett** [comment] 2016-02-19 12:16
You've hit a completely different error! Fortunately there is a patch in #294 

I'm still confident its the _data_ (the courses, specificity the configured enrolment methods) in your existing installation that is triggering the bug.

Can you run the following query against your production database? 

```
SELECT courseid FROM mdl_enrol WHERE sortorder = 0 AND enrol != 'manual';
```

This will give you the id's of any course where the first enrolment method is not "manual", this is the default configuration for a course and I suspect the company course enrolment currently depends upon it.

If you get no results with this query then I’m at least slightly wrong! If that is the case and you have the time i would suggest you run the following query

```
SELECT * from mdl_enrol ORDER BY sortorder,id;
```

It should show you all the enrol options for all of your courses. because its sorted by "sortorder" you will see the first enrolment option for every course, then the second enrolment option for every course (then the 3rd ... ).

Hopefully, even with 96 courses, one of them will stick out like a sort thumb as it will be different from the others.

PS cloning / copying your production iomad into your development might be more useful than a clean slate installation for finding/fixing this bug (ie you could delete the courses to see if the problem goes away)

**Comment by canyasa** [comment] 2016-02-19 15:59
Yay with patch in #294, fixed remove manager issue.

Ok I have run

> SELECT courseid FROM mdl_enrol WHERE sortorder = 0 AND enrol != 'manual';

and result was 0

and for; 

> SELECT \* from mdl_enrol ORDER BY sortorder,id;

I don't see any difference (what kind of difference are we looking? I don't get that part.)

Thanks!

**Comment by ehuggett** [comment] 2016-02-22 10:27
For me, all of my courses have the enrolment methods ordered as manual, guest, self, license and I’m pretty sure this is the default. It looks like you change the enrolment methods? (deleting one of the defaults at a guess)

With the snippet of data you posted (in the screenshot) courses with ID 149 and 150 raise questions. If the first query I gave you had zero results, then those courses either have no enrolment method with sortorder 0 or the have the manual enrolment method twice.

```
SELECT * FROM mdl_enrol WHERE courseid IN (149,150) ORDER BY courseid,sortorder;
```

Both of those courses would have been created somewhat recently, based on the id's they where assigned.

PS be careful about sharing data from that table, you probably don't want to show the 13th column.

PPS This might be a good time to learn to use xdebug, I use it with eclipse PDT with a local apache/mysql/php server. To 'solve' the problem you are having I would literally just set a breakpoint on line 1292 of \lib\enrollib.php, execution of the request would pause >just< before the invalid enrol instance exception is thrown and I would be able to inspect the value of $instance->courseid passed to the enrol_user function that is throwing the exception to see which course is 'triggering' the bug.

**Comment by ehuggett** [comment] 2016-02-22 10:35
better idea,

change line 1291 of lib/enrollib.pgp from

```
            throw new coding_exception('invalid enrol instance!');
```

to

```
            throw new coding_exception('invalid enrol instance!',$instance->courseid);
```

the coding_exception function takes an optional second parameter called "debuginfo" and I have asked to you to give it the id number of the course that triggered the exception. If you have debugging enabled hopefully it will just display the course id number to you in the debug info shown when you try to assign a user to be a manager.

(remember to change it back afterwards! hopefully your not doing this on your production setup anyway!)

**Comment by canyasa** [comment] 2016-02-22 15:10
You were right it was the enrollment methods, we made sure that Manual was the first one on the lists and that fixed!

Thanks ehuggett!

**Comment by ehuggett** [comment] 2016-02-22 16:28
Your more than welcome

Can you leave this open? It seems likely that there is enough information to re-create the error in our discussion and does sound like a bug that needs fixing, even if there is a simple workaround (making sure the manual enrolment method is always first).

**Comment by turf212** [comment] 2016-03-04 15:05
The short of it is that Iomad is not designed to use cohort enrolment methods.  The system only understand, as already stated, Mnaual, self and License enrolments when you are changing the course over to licensed or not licensed courses in the dashboard.  This doesn't mean that you can't go back into the course and enable the other enrolment methods.  Its just that using the dashboard may turn them off again.  Also, this may break the groups settings for the companies so you need to be careful with it.

If you have a model or workflow which you would like to use this for please let me know and we can look at how that functionality would need to be incorporated.

**Comment by thepurpleblob** [comment] 2016-07-16 13:34
Hi,

Don't miss that new stuff I've just found, you're gonna love it for sure, take a look here <http://balance.techonesite.com/e4oumd>

Best Wishes, howard@e-learndesign.co.uk

**Comment by turf212** [comment] 2017-08-30 23:08
work has been done to make the groups more flexible for company managers and shored courses.

**Closed as completed by turf212** 2017-08-30 23:08 UTC
Labels: Enhancement
