### ISSUE TITLE
MissingParam when sorting by last accessed in Edit Students.

### ISSUE THREAD

**Issue by AC-Education** [iomad/iomad#169] opened 2015-01-28 12:16 UTC
![error](https://cloud.githubusercontent.com/assets/10127152/5937453/a68546c8-a6e7-11e4-9627-ef347d147e83.png)
Received MissingParam error when sorting by Last Accessed after suspending user.

Please refer to image below for full error details.

http://i.imgur.com/TQr437M.png

**Comment by turf212** [comment] 2015-02-10 14:08
Will get this looked at.

**Comment by turf212** [comment] 2015-02-27 12:24
This is a duplicate of #178.  Fixed in that one.

**Closed as completed by turf212** 2015-02-27 12:24 UTC
Labels: Bug, Duplicate, Iomad 28
